### PR TITLE
Hotfix add CM support

### PR DESCRIPTION
**Pull request by zonky2**
Hotfix add CM support

see https://github.com/contao/contao-manager/issues/417#issuecomment-480254547

### CODE REVIEW

**Comment by richardhj** [comment]
Whats about just adding `metamodels/core` dependency?

**Comment by zonky2** [comment]
this is the copy of sub-bundles ... every repo has the core required

**Comment by richardhj** [comment]
If you add a `metamodels/core` dependency to this bundle, you do not have to duplicate the dependencies of the sub-bundles, don't you?

**Comment by discordier** [comment]
Nice idea @richardhj, I like this approach better.

**Comment by zonky2** [comment]
ok

**Pull request merged**
